### ISSUE TITLE
BUG: The package `optimum` is required to use Better Transformer.

### ISSUE THREAD

**Issue by ahmedosman2001** [Vaibhavs10/insanely-fast-whisper#81]
When i use Whisper without a CLI as recomeneded in the README,
```python
import torch
from transformers import pipeline

pipe = pipeline(
    "automatic-speech-recognition",
    model="openai/whisper-large-v3",
    torch_dtype=torch.float16,
    device="cuda", # or mps for Mac devices
    model_kwargs={"use_flash_attention_2": False}, # set to False for old GPUs
)

pipe.model = pipe.model.to_bettertransformer() # only if `use_flash_attention_2` is set to False

outputs = pipe("<FILE_NAME>",
               chunk_length_s=30,
               batch_size=24,
               return_timestamps=True)

outputs
```

I get this error `The package optimum is required to use Better Transformer.`
After reading around i realised i have to first install transformers with accelerate and optimum.
`pip install transformers accelerate optimum `
This maybe something that can be added to the README

**Comment by bt-nia** [comment]
probably related to this: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/75

**Comment by Vaibhavs10** [comment]
Thanks for the Bug report @ahmedosman2001 - I added it to the README. 🤗 

(Feel free to re-open if you have any other questions!)

**Comment by javadasoodeh** [comment]
The error occurs because the `Transformers` library now natively supports BetterTransformer optimizations for the Whisper model. Therefore, using `model.to_bettertransformer()` or `BetterTransformer.transform(model)` is no longer necessary.

## Solution:

1. **Upgrade `Transformers` and `Torch`:**

   ```bash
   pip install --upgrade transformers torch
   ```

2. **Update your code:**

   Remove the line:
   
   ```python
   pipe.model = pipe.model.to_bettertransformer()
   ```

   Your code should look like this:

   ```python
   from transformers import pipeline

   # Initialize the pipeline
   pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small")

   # Perform transcription
   outputs = pipe("path_to_audio_file.wav")

   # Print the transcription
   print(outputs)
   ```

By following these steps, you can resolve the ValueError and use the Whisper model effectively.
